/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AuthEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cdn": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "Database": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "Domain": {
      "api": string
      "type": "sst.sst.Linkable"
      "web": string
    }
    "ElectricSqlSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ElectricSqlSource": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExpoOwner": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExpoProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExpoToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOAuthClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOAuthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageProcessorFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LoopsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MarketingEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "NODE_TLS_REJECT_UNAUTHORIZED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonOrgId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NotifyEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "OptimisedStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PersonalEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "PosthogHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PosthogPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Stage": {
      "cookiePrefix": string
      "type": "sst.sst.Linkable"
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StripeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SyncEngine": {
      "secret": string
      "source": string
      "type": "sst.sst.Linkable"
    }
    "Web": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "anotherPersonalEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}