import { foreignKey, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { app } from '../app/app.sql';

export const branding = pgTable('branding', {
	appId: text('id').primaryKey().notNull(),
	icon: text('icon'),
	font: text('font').notNull(),
	lightLargeLogo: text('light_large_logo'),
	darkLargeLogo: text('dark_large_logo'),
	lightAccent: text('light_accent').notNull(),
	lightAccentHigh: text('light_accent_high').notNull(),
	lightAccentLow: text('light_accent_low').notNull(),
	lightForeground: text('light_foreground').notNull(),
	lightBackground: text('light_background').notNull(),
	lightGrey1: text('light_grey_1').notNull(),
	lightGrey2: text('light_grey_2').notNull(),
	lightGrey3: text('light_grey_3').notNull(),
	lightGrey4: text('light_grey_4').notNull(),
	lightGrey5: text('light_grey_5').notNull(),
	lightGrey6: text('light_grey_6').notNull(),
	lightGrey7: text('light_grey_7').notNull(),
	darkAccent: text('dark_accent').notNull(),
	darkAccentHigh: text('dark_accent_high').notNull(),
	darkAccentLow: text('dark_accent_low').notNull(),
	darkForeground: text('dark_foreground').notNull(),
	darkBackground: text('dark_background').notNull(),
	darkGrey1: text('dark_grey_1').notNull(),
	darkGrey2: text('dark_grey_2').notNull(),
	darkGrey3: text('dark_grey_3').notNull(),
	darkGrey4: text('dark_grey_4').notNull(),
	darkGrey5: text('dark_grey_5').notNull(),
	darkGrey6: text('dark_grey_6').notNull(),
	darkGrey7: text('dark_grey_7').notNull(),
	// Published fields
	publishedIcon: text('published_icon'),
	publishedFont: text('published_font'),
	publishedLightLargeLogo: text('published_light_large_logo'),
	publishedDarkLargeLogo: text('published_dark_large_logo'),
	publishedLightAccent: text('published_light_accent'),
	publishedLightAccentHigh: text('published_light_accent_high'),
	publishedLightAccentLow: text('published_light_accent_low'),
	publishedLightForeground: text('published_light_foreground'),
	publishedLightBackground: text('published_light_background'),
	publishedLightGrey1: text('published_light_grey_1'),
	publishedLightGrey2: text('published_light_grey_2'),
	publishedLightGrey3: text('published_light_grey_3'),
	publishedLightGrey4: text('published_light_grey_4'),
	publishedLightGrey5: text('published_light_grey_5'),
	publishedLightGrey6: text('published_light_grey_6'),
	publishedLightGrey7: text('published_light_grey_7'),
	publishedDarkAccent: text('published_dark_accent'),
	publishedDarkAccentHigh: text('published_dark_accent_high'),
	publishedDarkAccentLow: text('published_dark_accent_low'),
	publishedDarkForeground: text('published_dark_foreground'),
	publishedDarkBackground: text('published_dark_background'),
	publishedDarkGrey1: text('published_dark_grey_1'),
	publishedDarkGrey2: text('published_dark_grey_2'),
	publishedDarkGrey3: text('published_dark_grey_3'),
	publishedDarkGrey4: text('published_dark_grey_4'),
	publishedDarkGrey5: text('published_dark_grey_5'),
	publishedDarkGrey6: text('published_dark_grey_6'),
	publishedDarkGrey7: text('published_dark_grey_7'),
	publishedAt: timestamp('published_at'),
	createdAt: timestamp('created_at').notNull(),
	updatedAt: timestamp('updated_at').notNull(),
	deletedAt: timestamp('deleted_at'),
});

export const brandingToApp = foreignKey({
	columns: [branding.appId],
	foreignColumns: [app.id],
});
