export const secret = {
    BetterAuthSecret: new sst.Secret('BetterAuthSecret'),
    NeonOrgId: new sst.Secret('NeonOrgId'),
    NeonApiKey: new sst.Secret('NeonApiKey'),
    NeonProjectId: new sst.Secret('NeonProjectId'),
    NeonConnectionUri: new sst.Secret('NeonConnectionUri'),
    GoogleClientId: new sst.Secret('GoogleOAuthClientId'),
    GoogleClientSecret: new sst.Secret('GoogleOAuthClientSecret'),
    LoopsApiKey: new sst.Secret('LoopsApiKey'),
    ElectricSqlSource: new sst.Secret('ElectricSqlSource'),
    ElectricSqlSecret: new sst.Secret('ElectricSqlSecret'),
    ElectricCloudApiToken: new sst.Secret('ElectricCloudApiToken'),
    ElectricCloudProjectId: new sst.Secret('ElectricCloudProjectId'),
    PosthogPublicKey: new sst.Secret('PosthogPublicKey'),
    PosthogHost: new sst.Secret('PosthogHost'),
    StripeSecretKey: new sst.Secret('StripeSecretKey'),
    StripePublishableKey: new sst.Secret('StripePublishableKey'),
    StripeClientId: new sst.Secret('StripeClientId'),
    StripeWebhookSecret: new sst.Secret('StripeWebhookSecret'),
    EncryptionKey: new sst.Secret('EncryptionKey'),
    ExpoToken: new sst.Secret('ExpoToken'),
    ExpoProjectId: new sst.Secret('ExpoProjectId'),
    ExpoOwner: new sst.Secret('ExpoOwner'),
};
