import { neon, neonConfig, Pool } from "@neondatabase/serverless";
import { drizzle as drizzleWs } from "drizzle-orm/neon-serverless";
import { Resource } from "sst";
import ws from "ws";

neonConfig.webSocketConstructor = ws;
// const sql = neon(Resource.DatabaseUrl);
// @ts-ignore - Type will be generated by SST
const pool = new Pool({ connectionString: Resource.DatabaseUrl });

export const db = drizzleWs({ client: pool });
