/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingOnboardingRouteImport } from './routes/_marketing/onboarding'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingResourcesIndexRouteImport } from './routes/_marketing/resources/index'
import { Route as LoginLoginIndexRouteImport } from './routes/_login/login/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MarketingResourcesSlugRouteImport } from './routes/_marketing/resources/$slug'
import { Route as LoginLoginCodeRouteImport } from './routes/_login/login/code'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOnboardingRoute = MarketingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingResourcesIndexRoute = MarketingResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => MarketingRoute,
} as any)
const LoginLoginIndexRoute = LoginLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/_auth/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingResourcesSlugRoute = MarketingResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const LoginLoginCodeRoute = LoginLoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/_auth/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/onboarding': typeof MarketingOnboardingRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/resources/$slug': typeof MarketingResourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/login/': typeof LoginLoginIndexRoute
  '/resources/': typeof MarketingResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/onboarding': typeof MarketingOnboardingRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/resources/$slug': typeof MarketingResourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/login': typeof LoginLoginIndexRoute
  '/resources': typeof MarketingResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_login': typeof LoginRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/onboarding': typeof MarketingOnboardingRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/_login/login/code': typeof LoginLoginCodeRoute
  '/_marketing/resources/$slug': typeof MarketingResourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_login/login/': typeof LoginLoginIndexRoute
  '/_marketing/resources/': typeof MarketingResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/onboarding'
    | '/app/settings'
    | '/login/code'
    | '/resources/$slug'
    | '/api/auth/$'
    | '/app/'
    | '/login/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/onboarding'
    | '/app/settings'
    | '/login/code'
    | '/resources/$slug'
    | '/api/auth/$'
    | '/app'
    | '/login'
    | '/resources'
  id:
    | '__root__'
    | '/_login'
    | '/_marketing'
    | '/_marketing/about'
    | '/_marketing/onboarding'
    | '/_marketing/'
    | '/_auth/app/settings'
    | '/_login/login/code'
    | '/_marketing/resources/$slug'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_login/login/'
    | '/_marketing/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/onboarding': {
      id: '/_marketing/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof MarketingOnboardingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/resources/': {
      id: '/_marketing/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof MarketingResourcesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_login/login/': {
      id: '/_login/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/resources/$slug': {
      id: '/_marketing/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof MarketingResourcesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_login/login/code': {
      id: '/_login/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginLoginCodeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginLoginCodeRoute: typeof LoginLoginCodeRoute
  LoginLoginIndexRoute: typeof LoginLoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLoginCodeRoute: LoginLoginCodeRoute,
  LoginLoginIndexRoute: LoginLoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingOnboardingRoute: typeof MarketingOnboardingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingResourcesSlugRoute: typeof MarketingResourcesSlugRoute
  MarketingResourcesIndexRoute: typeof MarketingResourcesIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingOnboardingRoute: MarketingOnboardingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingResourcesSlugRoute: MarketingResourcesSlugRoute,
  MarketingResourcesIndexRoute: MarketingResourcesIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
