/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginLoginIndexRouteImport } from './routes/_login/login/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LoginLoginCodeRouteImport } from './routes/_login/login/code'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLoginIndexRoute = LoginLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/_auth/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLoginCodeRoute = LoginLoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/_auth/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/login/': typeof LoginLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/login': typeof LoginLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_login': typeof LoginRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/_login/login/code': typeof LoginLoginCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_login/login/': typeof LoginLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app/settings'
    | '/login/code'
    | '/api/auth/$'
    | '/app/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app/settings'
    | '/login/code'
    | '/api/auth/$'
    | '/app'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_login'
    | '/about'
    | '/_auth/app/settings'
    | '/_login/login/code'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_login/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/login/': {
      id: '/_login/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/login/code': {
      id: '/_login/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginLoginCodeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginLoginCodeRoute: typeof LoginLoginCodeRoute
  LoginLoginIndexRoute: typeof LoginLoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLoginCodeRoute: LoginLoginCodeRoute,
  LoginLoginIndexRoute: LoginLoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
