/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as UseCasesLoftRouteImport } from './routes/use-cases/loft'
import { Route as UseCasesKitchenRouteImport } from './routes/use-cases/kitchen'
import { Route as UseCasesExtensionRouteImport } from './routes/use-cases/extension'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as MarketingTmpRouteImport } from './routes/_marketing/tmp'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingHelpRouteImport } from './routes/_marketing/help'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as AuthSettingsRouteImport } from './routes/_auth/_settings'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/_onboarding'
import { Route as MarketingGuidesIndexRouteImport } from './routes/_marketing/guides/index'
import { Route as LoginLoginIndexRouteImport } from './routes/_login/login/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MarketingGuidesSlugRouteImport } from './routes/_marketing/guides/$slug'
import { Route as LoginLoginCodeRouteImport } from './routes/_login/login/code'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'
import { Route as AuthAppPrototypeChatRouteImport } from './routes/_auth/app/prototype-chat'
import { Route as AuthAppLabRouteImport } from './routes/_auth/app/lab'
import { Route as AuthOnboardingOnboardingIndexRouteImport } from './routes/_auth/_onboarding/onboarding/index'
import { Route as AuthSettingsSettingsNotificationsRouteImport } from './routes/_auth/_settings/settings/notifications'
import { Route as AuthSettingsSettingsBillingRouteImport } from './routes/_auth/_settings/settings/billing'
import { Route as AuthSettingsSettingsAccountRouteImport } from './routes/_auth/_settings/settings/account'
import { Route as AuthOnboardingOnboardingThankYouRouteImport } from './routes/_auth/_onboarding/onboarding/thank-you'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const UseCasesLoftRoute = UseCasesLoftRouteImport.update({
  id: '/use-cases/loft',
  path: '/use-cases/loft',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesKitchenRoute = UseCasesKitchenRouteImport.update({
  id: '/use-cases/kitchen',
  path: '/use-cases/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesExtensionRoute = UseCasesExtensionRouteImport.update({
  id: '/use-cases/extension',
  path: '/use-cases/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTmpRoute = MarketingTmpRouteImport.update({
  id: '/tmp',
  path: '/tmp',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpRoute = MarketingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const MarketingGuidesIndexRoute = MarketingGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => MarketingRoute,
} as any)
const LoginLoginIndexRoute = LoginLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingGuidesSlugRoute = MarketingGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const LoginLoginCodeRoute = LoginLoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => LoginRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppPrototypeChatRoute = AuthAppPrototypeChatRouteImport.update({
  id: '/app/prototype-chat',
  path: '/app/prototype-chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppLabRoute = AuthAppLabRouteImport.update({
  id: '/app/lab',
  path: '/app/lab',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingOnboardingIndexRoute =
  AuthOnboardingOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)
const AuthSettingsSettingsNotificationsRoute =
  AuthSettingsSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsSettingsBillingRoute =
  AuthSettingsSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsSettingsAccountRoute =
  AuthSettingsSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthOnboardingOnboardingThankYouRoute =
  AuthOnboardingOnboardingThankYouRouteImport.update({
    id: '/onboarding/thank-you',
    path: '/onboarding/thank-you',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/blog': typeof BlogRoute
  '/about': typeof MarketingAboutRoute
  '/help': typeof MarketingHelpRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/tmp': typeof MarketingTmpRoute
  '/api/users': typeof ApiUsersRoute
  '/use-cases/extension': typeof UseCasesExtensionRoute
  '/use-cases/kitchen': typeof UseCasesKitchenRoute
  '/use-cases/loft': typeof UseCasesLoftRoute
  '/app/lab': typeof AuthAppLabRoute
  '/app/prototype-chat': typeof AuthAppPrototypeChatRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/guides/$slug': typeof MarketingGuidesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/login/': typeof LoginLoginIndexRoute
  '/guides/': typeof MarketingGuidesIndexRoute
  '/onboarding/thank-you': typeof AuthOnboardingOnboardingThankYouRoute
  '/settings/account': typeof AuthSettingsSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsSettingsBillingRoute
  '/settings/notifications': typeof AuthSettingsSettingsNotificationsRoute
  '/onboarding/': typeof AuthOnboardingOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/blog': typeof BlogRoute
  '/about': typeof MarketingAboutRoute
  '/help': typeof MarketingHelpRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/tmp': typeof MarketingTmpRoute
  '/api/users': typeof ApiUsersRoute
  '/use-cases/extension': typeof UseCasesExtensionRoute
  '/use-cases/kitchen': typeof UseCasesKitchenRoute
  '/use-cases/loft': typeof UseCasesLoftRoute
  '/app/lab': typeof AuthAppLabRoute
  '/app/prototype-chat': typeof AuthAppPrototypeChatRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/login/code': typeof LoginLoginCodeRoute
  '/guides/$slug': typeof MarketingGuidesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/login': typeof LoginLoginIndexRoute
  '/guides': typeof MarketingGuidesIndexRoute
  '/onboarding/thank-you': typeof AuthOnboardingOnboardingThankYouRoute
  '/settings/account': typeof AuthSettingsSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsSettingsBillingRoute
  '/settings/notifications': typeof AuthSettingsSettingsNotificationsRoute
  '/onboarding': typeof AuthOnboardingOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_login': typeof LoginRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/blog': typeof BlogRoute
  '/_auth/_onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/_settings': typeof AuthSettingsRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/help': typeof MarketingHelpRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_marketing/tmp': typeof MarketingTmpRoute
  '/api/users': typeof ApiUsersRoute
  '/use-cases/extension': typeof UseCasesExtensionRoute
  '/use-cases/kitchen': typeof UseCasesKitchenRoute
  '/use-cases/loft': typeof UseCasesLoftRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_auth/app/lab': typeof AuthAppLabRoute
  '/_auth/app/prototype-chat': typeof AuthAppPrototypeChatRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/_login/login/code': typeof LoginLoginCodeRoute
  '/_marketing/guides/$slug': typeof MarketingGuidesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_login/login/': typeof LoginLoginIndexRoute
  '/_marketing/guides/': typeof MarketingGuidesIndexRoute
  '/_auth/_onboarding/onboarding/thank-you': typeof AuthOnboardingOnboardingThankYouRoute
  '/_auth/_settings/settings/account': typeof AuthSettingsSettingsAccountRoute
  '/_auth/_settings/settings/billing': typeof AuthSettingsSettingsBillingRoute
  '/_auth/_settings/settings/notifications': typeof AuthSettingsSettingsNotificationsRoute
  '/_auth/_onboarding/onboarding/': typeof AuthOnboardingOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/about'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/tmp'
    | '/api/users'
    | '/use-cases/extension'
    | '/use-cases/kitchen'
    | '/use-cases/loft'
    | '/app/lab'
    | '/app/prototype-chat'
    | '/app/settings'
    | '/login/code'
    | '/guides/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/'
    | '/login/'
    | '/guides/'
    | '/onboarding/thank-you'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/notifications'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/about'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/tmp'
    | '/api/users'
    | '/use-cases/extension'
    | '/use-cases/kitchen'
    | '/use-cases/loft'
    | '/app/lab'
    | '/app/prototype-chat'
    | '/app/settings'
    | '/login/code'
    | '/guides/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app'
    | '/login'
    | '/guides'
    | '/onboarding/thank-you'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/notifications'
    | '/onboarding'
  id:
    | '__root__'
    | '/_auth'
    | '/_login'
    | '/_marketing'
    | '/blog'
    | '/_auth/_onboarding'
    | '/_auth/_settings'
    | '/_marketing/about'
    | '/_marketing/help'
    | '/_marketing/privacy'
    | '/_marketing/terms'
    | '/_marketing/tmp'
    | '/api/users'
    | '/use-cases/extension'
    | '/use-cases/kitchen'
    | '/use-cases/loft'
    | '/_marketing/'
    | '/_auth/app/lab'
    | '/_auth/app/prototype-chat'
    | '/_auth/app/settings'
    | '/_login/login/code'
    | '/_marketing/guides/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_auth/app/'
    | '/_login/login/'
    | '/_marketing/guides/'
    | '/_auth/_onboarding/onboarding/thank-you'
    | '/_auth/_settings/settings/account'
    | '/_auth/_settings/settings/billing'
    | '/_auth/_settings/settings/notifications'
    | '/_auth/_onboarding/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  BlogRoute: typeof BlogRoute
  ApiUsersRoute: typeof ApiUsersRoute
  UseCasesExtensionRoute: typeof UseCasesExtensionRoute
  UseCasesKitchenRoute: typeof UseCasesKitchenRoute
  UseCasesLoftRoute: typeof UseCasesLoftRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/use-cases/loft': {
      id: '/use-cases/loft'
      path: '/use-cases/loft'
      fullPath: '/use-cases/loft'
      preLoaderRoute: typeof UseCasesLoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/kitchen': {
      id: '/use-cases/kitchen'
      path: '/use-cases/kitchen'
      fullPath: '/use-cases/kitchen'
      preLoaderRoute: typeof UseCasesKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/extension': {
      id: '/use-cases/extension'
      path: '/use-cases/extension'
      fullPath: '/use-cases/extension'
      preLoaderRoute: typeof UseCasesExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/tmp': {
      id: '/_marketing/tmp'
      path: '/tmp'
      fullPath: '/tmp'
      preLoaderRoute: typeof MarketingTmpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help': {
      id: '/_marketing/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MarketingHelpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/_settings': {
      id: '/_auth/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_onboarding': {
      id: '/_auth/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_marketing/guides/': {
      id: '/_marketing/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof MarketingGuidesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_login/login/': {
      id: '/_login/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/guides/$slug': {
      id: '/_marketing/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof MarketingGuidesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_login/login/code': {
      id: '/_login/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginLoginCodeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/prototype-chat': {
      id: '/_auth/app/prototype-chat'
      path: '/app/prototype-chat'
      fullPath: '/app/prototype-chat'
      preLoaderRoute: typeof AuthAppPrototypeChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/lab': {
      id: '/_auth/app/lab'
      path: '/app/lab'
      fullPath: '/app/lab'
      preLoaderRoute: typeof AuthAppLabRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_onboarding/onboarding/': {
      id: '/_auth/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthOnboardingOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/_settings/settings/notifications': {
      id: '/_auth/_settings/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/_settings/settings/billing': {
      id: '/_auth/_settings/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsSettingsBillingRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/_settings/settings/account': {
      id: '/_auth/_settings/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/_onboarding/onboarding/thank-you': {
      id: '/_auth/_onboarding/onboarding/thank-you'
      path: '/onboarding/thank-you'
      fullPath: '/onboarding/thank-you'
      preLoaderRoute: typeof AuthOnboardingOnboardingThankYouRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
  }
}

interface AuthOnboardingRouteChildren {
  AuthOnboardingOnboardingThankYouRoute: typeof AuthOnboardingOnboardingThankYouRoute
  AuthOnboardingOnboardingIndexRoute: typeof AuthOnboardingOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingOnboardingThankYouRoute: AuthOnboardingOnboardingThankYouRoute,
  AuthOnboardingOnboardingIndexRoute: AuthOnboardingOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsSettingsAccountRoute: typeof AuthSettingsSettingsAccountRoute
  AuthSettingsSettingsBillingRoute: typeof AuthSettingsSettingsBillingRoute
  AuthSettingsSettingsNotificationsRoute: typeof AuthSettingsSettingsNotificationsRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsSettingsAccountRoute: AuthSettingsSettingsAccountRoute,
  AuthSettingsSettingsBillingRoute: AuthSettingsSettingsBillingRoute,
  AuthSettingsSettingsNotificationsRoute:
    AuthSettingsSettingsNotificationsRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthAppLabRoute: typeof AuthAppLabRoute
  AuthAppPrototypeChatRoute: typeof AuthAppPrototypeChatRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthAppLabRoute: AuthAppLabRoute,
  AuthAppPrototypeChatRoute: AuthAppPrototypeChatRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LoginRouteChildren {
  LoginLoginCodeRoute: typeof LoginLoginCodeRoute
  LoginLoginIndexRoute: typeof LoginLoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLoginCodeRoute: LoginLoginCodeRoute,
  LoginLoginIndexRoute: LoginLoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingHelpRoute: typeof MarketingHelpRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingTmpRoute: typeof MarketingTmpRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingGuidesSlugRoute: typeof MarketingGuidesSlugRoute
  MarketingGuidesIndexRoute: typeof MarketingGuidesIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingHelpRoute: MarketingHelpRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingTmpRoute: MarketingTmpRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingGuidesSlugRoute: MarketingGuidesSlugRoute,
  MarketingGuidesIndexRoute: MarketingGuidesIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  BlogRoute: BlogRoute,
  ApiUsersRoute: ApiUsersRoute,
  UseCasesExtensionRoute: UseCasesExtensionRoute,
  UseCasesKitchenRoute: UseCasesKitchenRoute,
  UseCasesLoftRoute: UseCasesLoftRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
