/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/_dashboard";
import { Route as AuthenticatedDashboardDesignRouteImport } from "./routes/_authenticated/_dashboard/_design";
import { Route as AuthenticatedDashboardDesignDesignBrandingRouteImport } from "./routes/_authenticated/_dashboard/_design/design/branding";
import { Route as AuthenticatedDashboardDesignDesignLayoutRouteImport } from "./routes/_authenticated/_dashboard/_design/design/layout";
import { Route as AuthenticatedDashboardDesignDesignNotificationsRouteImport } from "./routes/_authenticated/_dashboard/_design/design/notifications";
import { Route as AuthenticatedDashboardDesignDesignPagesRouteImport } from "./routes/_authenticated/_dashboard/_design/design/pages";
import { Route as AuthenticatedDashboardMembersRouteImport } from "./routes/_authenticated/_dashboard/_members";
import { Route as AuthenticatedDashboardMembersMembersIndexRouteImport } from "./routes/_authenticated/_dashboard/_members/members/index";
import { Route as AuthenticatedDashboardReleasesRouteImport } from "./routes/_authenticated/_dashboard/_releases";
import { Route as AuthenticatedDashboardReleasesReleasesAndroidRouteImport } from "./routes/_authenticated/_dashboard/_releases/releases/android";
import { Route as AuthenticatedDashboardReleasesReleasesIosRouteImport } from "./routes/_authenticated/_dashboard/_releases/releases/ios";
import { Route as AuthenticatedDashboardReleasesReleasesOverviewRouteImport } from "./routes/_authenticated/_dashboard/_releases/releases/overview";
import { Route as AuthenticatedDashboardReleasesReleasesWebRouteImport } from "./routes/_authenticated/_dashboard/_releases/releases/web";
import { Route as AuthenticatedDashboardSalesRouteImport } from "./routes/_authenticated/_dashboard/_sales";
import { Route as AuthenticatedDashboardSalesSalesDiscountCodesRouteImport } from "./routes/_authenticated/_dashboard/_sales/sales/discount-codes";
import { Route as AuthenticatedDashboardSalesSalesPricingRouteImport } from "./routes/_authenticated/_dashboard/_sales/sales/pricing";
import { Route as AuthenticatedDashboardSalesSalesTransactionsRouteImport } from "./routes/_authenticated/_dashboard/_sales/sales/transactions";
import { Route as AuthenticatedDashboardSettingsRouteImport } from "./routes/_authenticated/_dashboard/_settings";
import { Route as AuthenticatedDashboardSettingsSettingsAccountRouteImport } from "./routes/_authenticated/_dashboard/_settings/settings/account";
import { Route as AuthenticatedDashboardSettingsSettingsBillingRouteImport } from "./routes/_authenticated/_dashboard/_settings/settings/billing";
import { Route as AuthenticatedDashboardSettingsSettingsIntegrationsRouteImport } from "./routes/_authenticated/_dashboard/_settings/settings/integrations";
import { Route as AuthenticatedDashboardSettingsSettingsNotificationsRouteImport } from "./routes/_authenticated/_dashboard/_settings/settings/notifications";
import { Route as AuthenticatedDashboardIndexRouteImport } from "./routes/_authenticated/_dashboard/index";
import { Route as AuthenticatedDashboardMediaRouteImport } from "./routes/_authenticated/_dashboard/media";
import { Route as AuthenticatedDashboardProductsProductIdRouteImport } from "./routes/_authenticated/_dashboard/products/$productId";
import { Route as AuthenticatedDashboardProductsIndexRouteImport } from "./routes/_authenticated/_dashboard/products/index";
import { Route as AuthenticatedOnboardingRouteImport } from "./routes/_authenticated/_onboarding";
import { Route as AuthenticatedOnboardingOnboardingPlanRouteImport } from "./routes/_authenticated/_onboarding/onboarding/plan";
import { Route as AuthenticatedOnboardingOnboardingProductRouteImport } from "./routes/_authenticated/_onboarding/onboarding/product";
import { Route as AuthenticatedOnboardingOnboardingProfileRouteImport } from "./routes/_authenticated/_onboarding/onboarding/profile";
import { Route as AuthenticatedOnboardingOnboardingWorkspaceRouteImport } from "./routes/_authenticated/_onboarding/onboarding/workspace";
import { Route as LoginRouteImport } from "./routes/_login";
import { Route as LoginLoginCodeRouteImport } from "./routes/_login/login/code";
import { Route as LoginLoginIndexRouteImport } from "./routes/_login/login/index";
import { Route as ApiSplatRouteImport } from "./routes/api/$";
import { Route as AuthSplatRouteImport } from "./routes/auth/$";

const LoginRoute = LoginRouteImport.update({
	id: "/_login",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
	id: "/_authenticated",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthSplatRoute = AuthSplatRouteImport.update({
	id: "/auth/$",
	path: "/auth/$",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
	id: "/api/$",
	path: "/api/$",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
	id: "/_onboarding",
	getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
	id: "/_dashboard",
	getParentRoute: () => AuthenticatedRoute,
} as any);
const LoginLoginIndexRoute = LoginLoginIndexRouteImport.update({
	id: "/login/",
	path: "/login/",
	getParentRoute: () => LoginRoute,
} as any);
const AuthenticatedDashboardIndexRoute =
	AuthenticatedDashboardIndexRouteImport.update({
		id: "/",
		path: "/",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const LoginLoginCodeRoute = LoginLoginCodeRouteImport.update({
	id: "/login/code",
	path: "/login/code",
	getParentRoute: () => LoginRoute,
} as any);
const AuthenticatedDashboardMediaRoute =
	AuthenticatedDashboardMediaRouteImport.update({
		id: "/media",
		path: "/media",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardSettingsRoute =
	AuthenticatedDashboardSettingsRouteImport.update({
		id: "/_settings",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardSalesRoute =
	AuthenticatedDashboardSalesRouteImport.update({
		id: "/_sales",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardReleasesRoute =
	AuthenticatedDashboardReleasesRouteImport.update({
		id: "/_releases",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardMembersRoute =
	AuthenticatedDashboardMembersRouteImport.update({
		id: "/_members",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardDesignRoute =
	AuthenticatedDashboardDesignRouteImport.update({
		id: "/_design",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardProductsIndexRoute =
	AuthenticatedDashboardProductsIndexRouteImport.update({
		id: "/products/",
		path: "/products/",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedOnboardingOnboardingWorkspaceRoute =
	AuthenticatedOnboardingOnboardingWorkspaceRouteImport.update({
		id: "/onboarding/workspace",
		path: "/onboarding/workspace",
		getParentRoute: () => AuthenticatedOnboardingRoute,
	} as any);
const AuthenticatedOnboardingOnboardingProfileRoute =
	AuthenticatedOnboardingOnboardingProfileRouteImport.update({
		id: "/onboarding/profile",
		path: "/onboarding/profile",
		getParentRoute: () => AuthenticatedOnboardingRoute,
	} as any);
const AuthenticatedOnboardingOnboardingProductRoute =
	AuthenticatedOnboardingOnboardingProductRouteImport.update({
		id: "/onboarding/product",
		path: "/onboarding/product",
		getParentRoute: () => AuthenticatedOnboardingRoute,
	} as any);
const AuthenticatedOnboardingOnboardingPlanRoute =
	AuthenticatedOnboardingOnboardingPlanRouteImport.update({
		id: "/onboarding/plan",
		path: "/onboarding/plan",
		getParentRoute: () => AuthenticatedOnboardingRoute,
	} as any);
const AuthenticatedDashboardProductsProductIdRoute =
	AuthenticatedDashboardProductsProductIdRouteImport.update({
		id: "/products/$productId",
		path: "/products/$productId",
		getParentRoute: () => AuthenticatedDashboardRoute,
	} as any);
const AuthenticatedDashboardMembersMembersIndexRoute =
	AuthenticatedDashboardMembersMembersIndexRouteImport.update({
		id: "/members/",
		path: "/members/",
		getParentRoute: () => AuthenticatedDashboardMembersRoute,
	} as any);
const AuthenticatedDashboardSettingsSettingsNotificationsRoute =
	AuthenticatedDashboardSettingsSettingsNotificationsRouteImport.update({
		id: "/settings/notifications",
		path: "/settings/notifications",
		getParentRoute: () => AuthenticatedDashboardSettingsRoute,
	} as any);
const AuthenticatedDashboardSettingsSettingsIntegrationsRoute =
	AuthenticatedDashboardSettingsSettingsIntegrationsRouteImport.update({
		id: "/settings/integrations",
		path: "/settings/integrations",
		getParentRoute: () => AuthenticatedDashboardSettingsRoute,
	} as any);
const AuthenticatedDashboardSettingsSettingsBillingRoute =
	AuthenticatedDashboardSettingsSettingsBillingRouteImport.update({
		id: "/settings/billing",
		path: "/settings/billing",
		getParentRoute: () => AuthenticatedDashboardSettingsRoute,
	} as any);
const AuthenticatedDashboardSettingsSettingsAccountRoute =
	AuthenticatedDashboardSettingsSettingsAccountRouteImport.update({
		id: "/settings/account",
		path: "/settings/account",
		getParentRoute: () => AuthenticatedDashboardSettingsRoute,
	} as any);
const AuthenticatedDashboardSalesSalesTransactionsRoute =
	AuthenticatedDashboardSalesSalesTransactionsRouteImport.update({
		id: "/sales/transactions",
		path: "/sales/transactions",
		getParentRoute: () => AuthenticatedDashboardSalesRoute,
	} as any);
const AuthenticatedDashboardSalesSalesPricingRoute =
	AuthenticatedDashboardSalesSalesPricingRouteImport.update({
		id: "/sales/pricing",
		path: "/sales/pricing",
		getParentRoute: () => AuthenticatedDashboardSalesRoute,
	} as any);
const AuthenticatedDashboardSalesSalesDiscountCodesRoute =
	AuthenticatedDashboardSalesSalesDiscountCodesRouteImport.update({
		id: "/sales/discount-codes",
		path: "/sales/discount-codes",
		getParentRoute: () => AuthenticatedDashboardSalesRoute,
	} as any);
const AuthenticatedDashboardReleasesReleasesWebRoute =
	AuthenticatedDashboardReleasesReleasesWebRouteImport.update({
		id: "/releases/web",
		path: "/releases/web",
		getParentRoute: () => AuthenticatedDashboardReleasesRoute,
	} as any);
const AuthenticatedDashboardReleasesReleasesOverviewRoute =
	AuthenticatedDashboardReleasesReleasesOverviewRouteImport.update({
		id: "/releases/overview",
		path: "/releases/overview",
		getParentRoute: () => AuthenticatedDashboardReleasesRoute,
	} as any);
const AuthenticatedDashboardReleasesReleasesIosRoute =
	AuthenticatedDashboardReleasesReleasesIosRouteImport.update({
		id: "/releases/ios",
		path: "/releases/ios",
		getParentRoute: () => AuthenticatedDashboardReleasesRoute,
	} as any);
const AuthenticatedDashboardReleasesReleasesAndroidRoute =
	AuthenticatedDashboardReleasesReleasesAndroidRouteImport.update({
		id: "/releases/android",
		path: "/releases/android",
		getParentRoute: () => AuthenticatedDashboardReleasesRoute,
	} as any);
const AuthenticatedDashboardDesignDesignPagesRoute =
	AuthenticatedDashboardDesignDesignPagesRouteImport.update({
		id: "/design/pages",
		path: "/design/pages",
		getParentRoute: () => AuthenticatedDashboardDesignRoute,
	} as any);
const AuthenticatedDashboardDesignDesignNotificationsRoute =
	AuthenticatedDashboardDesignDesignNotificationsRouteImport.update({
		id: "/design/notifications",
		path: "/design/notifications",
		getParentRoute: () => AuthenticatedDashboardDesignRoute,
	} as any);
const AuthenticatedDashboardDesignDesignLayoutRoute =
	AuthenticatedDashboardDesignDesignLayoutRouteImport.update({
		id: "/design/layout",
		path: "/design/layout",
		getParentRoute: () => AuthenticatedDashboardDesignRoute,
	} as any);
const AuthenticatedDashboardDesignDesignBrandingRoute =
	AuthenticatedDashboardDesignDesignBrandingRouteImport.update({
		id: "/design/branding",
		path: "/design/branding",
		getParentRoute: () => AuthenticatedDashboardDesignRoute,
	} as any);

export interface FileRoutesByFullPath {
	"/api/$": typeof ApiSplatRoute;
	"/auth/$": typeof AuthSplatRoute;
	"/media": typeof AuthenticatedDashboardMediaRoute;
	"/login/code": typeof LoginLoginCodeRoute;
	"/": typeof AuthenticatedDashboardIndexRoute;
	"/login": typeof LoginLoginIndexRoute;
	"/products/$productId": typeof AuthenticatedDashboardProductsProductIdRoute;
	"/onboarding/plan": typeof AuthenticatedOnboardingOnboardingPlanRoute;
	"/onboarding/product": typeof AuthenticatedOnboardingOnboardingProductRoute;
	"/onboarding/profile": typeof AuthenticatedOnboardingOnboardingProfileRoute;
	"/onboarding/workspace": typeof AuthenticatedOnboardingOnboardingWorkspaceRoute;
	"/products": typeof AuthenticatedDashboardProductsIndexRoute;
	"/design/branding": typeof AuthenticatedDashboardDesignDesignBrandingRoute;
	"/design/layout": typeof AuthenticatedDashboardDesignDesignLayoutRoute;
	"/design/notifications": typeof AuthenticatedDashboardDesignDesignNotificationsRoute;
	"/design/pages": typeof AuthenticatedDashboardDesignDesignPagesRoute;
	"/releases/android": typeof AuthenticatedDashboardReleasesReleasesAndroidRoute;
	"/releases/ios": typeof AuthenticatedDashboardReleasesReleasesIosRoute;
	"/releases/overview": typeof AuthenticatedDashboardReleasesReleasesOverviewRoute;
	"/releases/web": typeof AuthenticatedDashboardReleasesReleasesWebRoute;
	"/sales/discount-codes": typeof AuthenticatedDashboardSalesSalesDiscountCodesRoute;
	"/sales/pricing": typeof AuthenticatedDashboardSalesSalesPricingRoute;
	"/sales/transactions": typeof AuthenticatedDashboardSalesSalesTransactionsRoute;
	"/settings/account": typeof AuthenticatedDashboardSettingsSettingsAccountRoute;
	"/settings/billing": typeof AuthenticatedDashboardSettingsSettingsBillingRoute;
	"/settings/integrations": typeof AuthenticatedDashboardSettingsSettingsIntegrationsRoute;
	"/settings/notifications": typeof AuthenticatedDashboardSettingsSettingsNotificationsRoute;
	"/members": typeof AuthenticatedDashboardMembersMembersIndexRoute;
}
export interface FileRoutesByTo {
	"/api/$": typeof ApiSplatRoute;
	"/auth/$": typeof AuthSplatRoute;
	"/media": typeof AuthenticatedDashboardMediaRoute;
	"/login/code": typeof LoginLoginCodeRoute;
	"/": typeof AuthenticatedDashboardIndexRoute;
	"/login": typeof LoginLoginIndexRoute;
	"/products/$productId": typeof AuthenticatedDashboardProductsProductIdRoute;
	"/onboarding/plan": typeof AuthenticatedOnboardingOnboardingPlanRoute;
	"/onboarding/product": typeof AuthenticatedOnboardingOnboardingProductRoute;
	"/onboarding/profile": typeof AuthenticatedOnboardingOnboardingProfileRoute;
	"/onboarding/workspace": typeof AuthenticatedOnboardingOnboardingWorkspaceRoute;
	"/products": typeof AuthenticatedDashboardProductsIndexRoute;
	"/design/branding": typeof AuthenticatedDashboardDesignDesignBrandingRoute;
	"/design/layout": typeof AuthenticatedDashboardDesignDesignLayoutRoute;
	"/design/notifications": typeof AuthenticatedDashboardDesignDesignNotificationsRoute;
	"/design/pages": typeof AuthenticatedDashboardDesignDesignPagesRoute;
	"/releases/android": typeof AuthenticatedDashboardReleasesReleasesAndroidRoute;
	"/releases/ios": typeof AuthenticatedDashboardReleasesReleasesIosRoute;
	"/releases/overview": typeof AuthenticatedDashboardReleasesReleasesOverviewRoute;
	"/releases/web": typeof AuthenticatedDashboardReleasesReleasesWebRoute;
	"/sales/discount-codes": typeof AuthenticatedDashboardSalesSalesDiscountCodesRoute;
	"/sales/pricing": typeof AuthenticatedDashboardSalesSalesPricingRoute;
	"/sales/transactions": typeof AuthenticatedDashboardSalesSalesTransactionsRoute;
	"/settings/account": typeof AuthenticatedDashboardSettingsSettingsAccountRoute;
	"/settings/billing": typeof AuthenticatedDashboardSettingsSettingsBillingRoute;
	"/settings/integrations": typeof AuthenticatedDashboardSettingsSettingsIntegrationsRoute;
	"/settings/notifications": typeof AuthenticatedDashboardSettingsSettingsNotificationsRoute;
	"/members": typeof AuthenticatedDashboardMembersMembersIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/_authenticated": typeof AuthenticatedRouteWithChildren;
	"/_login": typeof LoginRouteWithChildren;
	"/_authenticated/_dashboard": typeof AuthenticatedDashboardRouteWithChildren;
	"/_authenticated/_onboarding": typeof AuthenticatedOnboardingRouteWithChildren;
	"/api/$": typeof ApiSplatRoute;
	"/auth/$": typeof AuthSplatRoute;
	"/_authenticated/_dashboard/_design": typeof AuthenticatedDashboardDesignRouteWithChildren;
	"/_authenticated/_dashboard/_members": typeof AuthenticatedDashboardMembersRouteWithChildren;
	"/_authenticated/_dashboard/_releases": typeof AuthenticatedDashboardReleasesRouteWithChildren;
	"/_authenticated/_dashboard/_sales": typeof AuthenticatedDashboardSalesRouteWithChildren;
	"/_authenticated/_dashboard/_settings": typeof AuthenticatedDashboardSettingsRouteWithChildren;
	"/_authenticated/_dashboard/media": typeof AuthenticatedDashboardMediaRoute;
	"/_login/login/code": typeof LoginLoginCodeRoute;
	"/_authenticated/_dashboard/": typeof AuthenticatedDashboardIndexRoute;
	"/_login/login/": typeof LoginLoginIndexRoute;
	"/_authenticated/_dashboard/products/$productId": typeof AuthenticatedDashboardProductsProductIdRoute;
	"/_authenticated/_onboarding/onboarding/plan": typeof AuthenticatedOnboardingOnboardingPlanRoute;
	"/_authenticated/_onboarding/onboarding/product": typeof AuthenticatedOnboardingOnboardingProductRoute;
	"/_authenticated/_onboarding/onboarding/profile": typeof AuthenticatedOnboardingOnboardingProfileRoute;
	"/_authenticated/_onboarding/onboarding/workspace": typeof AuthenticatedOnboardingOnboardingWorkspaceRoute;
	"/_authenticated/_dashboard/products/": typeof AuthenticatedDashboardProductsIndexRoute;
	"/_authenticated/_dashboard/_design/design/branding": typeof AuthenticatedDashboardDesignDesignBrandingRoute;
	"/_authenticated/_dashboard/_design/design/layout": typeof AuthenticatedDashboardDesignDesignLayoutRoute;
	"/_authenticated/_dashboard/_design/design/notifications": typeof AuthenticatedDashboardDesignDesignNotificationsRoute;
	"/_authenticated/_dashboard/_design/design/pages": typeof AuthenticatedDashboardDesignDesignPagesRoute;
	"/_authenticated/_dashboard/_releases/releases/android": typeof AuthenticatedDashboardReleasesReleasesAndroidRoute;
	"/_authenticated/_dashboard/_releases/releases/ios": typeof AuthenticatedDashboardReleasesReleasesIosRoute;
	"/_authenticated/_dashboard/_releases/releases/overview": typeof AuthenticatedDashboardReleasesReleasesOverviewRoute;
	"/_authenticated/_dashboard/_releases/releases/web": typeof AuthenticatedDashboardReleasesReleasesWebRoute;
	"/_authenticated/_dashboard/_sales/sales/discount-codes": typeof AuthenticatedDashboardSalesSalesDiscountCodesRoute;
	"/_authenticated/_dashboard/_sales/sales/pricing": typeof AuthenticatedDashboardSalesSalesPricingRoute;
	"/_authenticated/_dashboard/_sales/sales/transactions": typeof AuthenticatedDashboardSalesSalesTransactionsRoute;
	"/_authenticated/_dashboard/_settings/settings/account": typeof AuthenticatedDashboardSettingsSettingsAccountRoute;
	"/_authenticated/_dashboard/_settings/settings/billing": typeof AuthenticatedDashboardSettingsSettingsBillingRoute;
	"/_authenticated/_dashboard/_settings/settings/integrations": typeof AuthenticatedDashboardSettingsSettingsIntegrationsRoute;
	"/_authenticated/_dashboard/_settings/settings/notifications": typeof AuthenticatedDashboardSettingsSettingsNotificationsRoute;
	"/_authenticated/_dashboard/_members/members/": typeof AuthenticatedDashboardMembersMembersIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/api/$"
		| "/auth/$"
		| "/media"
		| "/login/code"
		| "/"
		| "/login"
		| "/products/$productId"
		| "/onboarding/plan"
		| "/onboarding/product"
		| "/onboarding/profile"
		| "/onboarding/workspace"
		| "/products"
		| "/design/branding"
		| "/design/layout"
		| "/design/notifications"
		| "/design/pages"
		| "/releases/android"
		| "/releases/ios"
		| "/releases/overview"
		| "/releases/web"
		| "/sales/discount-codes"
		| "/sales/pricing"
		| "/sales/transactions"
		| "/settings/account"
		| "/settings/billing"
		| "/settings/integrations"
		| "/settings/notifications"
		| "/members";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/api/$"
		| "/auth/$"
		| "/media"
		| "/login/code"
		| "/"
		| "/login"
		| "/products/$productId"
		| "/onboarding/plan"
		| "/onboarding/product"
		| "/onboarding/profile"
		| "/onboarding/workspace"
		| "/products"
		| "/design/branding"
		| "/design/layout"
		| "/design/notifications"
		| "/design/pages"
		| "/releases/android"
		| "/releases/ios"
		| "/releases/overview"
		| "/releases/web"
		| "/sales/discount-codes"
		| "/sales/pricing"
		| "/sales/transactions"
		| "/settings/account"
		| "/settings/billing"
		| "/settings/integrations"
		| "/settings/notifications"
		| "/members";
	id:
		| "__root__"
		| "/_authenticated"
		| "/_login"
		| "/_authenticated/_dashboard"
		| "/_authenticated/_onboarding"
		| "/api/$"
		| "/auth/$"
		| "/_authenticated/_dashboard/_design"
		| "/_authenticated/_dashboard/_members"
		| "/_authenticated/_dashboard/_releases"
		| "/_authenticated/_dashboard/_sales"
		| "/_authenticated/_dashboard/_settings"
		| "/_authenticated/_dashboard/media"
		| "/_login/login/code"
		| "/_authenticated/_dashboard/"
		| "/_login/login/"
		| "/_authenticated/_dashboard/products/$productId"
		| "/_authenticated/_onboarding/onboarding/plan"
		| "/_authenticated/_onboarding/onboarding/product"
		| "/_authenticated/_onboarding/onboarding/profile"
		| "/_authenticated/_onboarding/onboarding/workspace"
		| "/_authenticated/_dashboard/products/"
		| "/_authenticated/_dashboard/_design/design/branding"
		| "/_authenticated/_dashboard/_design/design/layout"
		| "/_authenticated/_dashboard/_design/design/notifications"
		| "/_authenticated/_dashboard/_design/design/pages"
		| "/_authenticated/_dashboard/_releases/releases/android"
		| "/_authenticated/_dashboard/_releases/releases/ios"
		| "/_authenticated/_dashboard/_releases/releases/overview"
		| "/_authenticated/_dashboard/_releases/releases/web"
		| "/_authenticated/_dashboard/_sales/sales/discount-codes"
		| "/_authenticated/_dashboard/_sales/sales/pricing"
		| "/_authenticated/_dashboard/_sales/sales/transactions"
		| "/_authenticated/_dashboard/_settings/settings/account"
		| "/_authenticated/_dashboard/_settings/settings/billing"
		| "/_authenticated/_dashboard/_settings/settings/integrations"
		| "/_authenticated/_dashboard/_settings/settings/notifications"
		| "/_authenticated/_dashboard/_members/members/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
	LoginRoute: typeof LoginRouteWithChildren;
	ApiSplatRoute: typeof ApiSplatRoute;
	AuthSplatRoute: typeof AuthSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/_login": {
			id: "/_login";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authenticated": {
			id: "/_authenticated";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/$": {
			id: "/auth/$";
			path: "/auth/$";
			fullPath: "/auth/$";
			preLoaderRoute: typeof AuthSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/$": {
			id: "/api/$";
			path: "/api/$";
			fullPath: "/api/$";
			preLoaderRoute: typeof ApiSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authenticated/_onboarding": {
			id: "/_authenticated/_onboarding";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedOnboardingRouteImport;
			parentRoute: typeof AuthenticatedRoute;
		};
		"/_authenticated/_dashboard": {
			id: "/_authenticated/_dashboard";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
			parentRoute: typeof AuthenticatedRoute;
		};
		"/_login/login/": {
			id: "/_login/login/";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginLoginIndexRouteImport;
			parentRoute: typeof LoginRoute;
		};
		"/_authenticated/_dashboard/": {
			id: "/_authenticated/_dashboard/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_login/login/code": {
			id: "/_login/login/code";
			path: "/login/code";
			fullPath: "/login/code";
			preLoaderRoute: typeof LoginLoginCodeRouteImport;
			parentRoute: typeof LoginRoute;
		};
		"/_authenticated/_dashboard/media": {
			id: "/_authenticated/_dashboard/media";
			path: "/media";
			fullPath: "/media";
			preLoaderRoute: typeof AuthenticatedDashboardMediaRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_settings": {
			id: "/_authenticated/_dashboard/_settings";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_sales": {
			id: "/_authenticated/_dashboard/_sales";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardSalesRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_releases": {
			id: "/_authenticated/_dashboard/_releases";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardReleasesRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_members": {
			id: "/_authenticated/_dashboard/_members";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardMembersRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_design": {
			id: "/_authenticated/_dashboard/_design";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthenticatedDashboardDesignRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/products/": {
			id: "/_authenticated/_dashboard/products/";
			path: "/products";
			fullPath: "/products";
			preLoaderRoute: typeof AuthenticatedDashboardProductsIndexRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_onboarding/onboarding/workspace": {
			id: "/_authenticated/_onboarding/onboarding/workspace";
			path: "/onboarding/workspace";
			fullPath: "/onboarding/workspace";
			preLoaderRoute: typeof AuthenticatedOnboardingOnboardingWorkspaceRouteImport;
			parentRoute: typeof AuthenticatedOnboardingRoute;
		};
		"/_authenticated/_onboarding/onboarding/profile": {
			id: "/_authenticated/_onboarding/onboarding/profile";
			path: "/onboarding/profile";
			fullPath: "/onboarding/profile";
			preLoaderRoute: typeof AuthenticatedOnboardingOnboardingProfileRouteImport;
			parentRoute: typeof AuthenticatedOnboardingRoute;
		};
		"/_authenticated/_onboarding/onboarding/product": {
			id: "/_authenticated/_onboarding/onboarding/product";
			path: "/onboarding/product";
			fullPath: "/onboarding/product";
			preLoaderRoute: typeof AuthenticatedOnboardingOnboardingProductRouteImport;
			parentRoute: typeof AuthenticatedOnboardingRoute;
		};
		"/_authenticated/_onboarding/onboarding/plan": {
			id: "/_authenticated/_onboarding/onboarding/plan";
			path: "/onboarding/plan";
			fullPath: "/onboarding/plan";
			preLoaderRoute: typeof AuthenticatedOnboardingOnboardingPlanRouteImport;
			parentRoute: typeof AuthenticatedOnboardingRoute;
		};
		"/_authenticated/_dashboard/products/$productId": {
			id: "/_authenticated/_dashboard/products/$productId";
			path: "/products/$productId";
			fullPath: "/products/$productId";
			preLoaderRoute: typeof AuthenticatedDashboardProductsProductIdRouteImport;
			parentRoute: typeof AuthenticatedDashboardRoute;
		};
		"/_authenticated/_dashboard/_members/members/": {
			id: "/_authenticated/_dashboard/_members/members/";
			path: "/members";
			fullPath: "/members";
			preLoaderRoute: typeof AuthenticatedDashboardMembersMembersIndexRouteImport;
			parentRoute: typeof AuthenticatedDashboardMembersRoute;
		};
		"/_authenticated/_dashboard/_settings/settings/notifications": {
			id: "/_authenticated/_dashboard/_settings/settings/notifications";
			path: "/settings/notifications";
			fullPath: "/settings/notifications";
			preLoaderRoute: typeof AuthenticatedDashboardSettingsSettingsNotificationsRouteImport;
			parentRoute: typeof AuthenticatedDashboardSettingsRoute;
		};
		"/_authenticated/_dashboard/_settings/settings/integrations": {
			id: "/_authenticated/_dashboard/_settings/settings/integrations";
			path: "/settings/integrations";
			fullPath: "/settings/integrations";
			preLoaderRoute: typeof AuthenticatedDashboardSettingsSettingsIntegrationsRouteImport;
			parentRoute: typeof AuthenticatedDashboardSettingsRoute;
		};
		"/_authenticated/_dashboard/_settings/settings/billing": {
			id: "/_authenticated/_dashboard/_settings/settings/billing";
			path: "/settings/billing";
			fullPath: "/settings/billing";
			preLoaderRoute: typeof AuthenticatedDashboardSettingsSettingsBillingRouteImport;
			parentRoute: typeof AuthenticatedDashboardSettingsRoute;
		};
		"/_authenticated/_dashboard/_settings/settings/account": {
			id: "/_authenticated/_dashboard/_settings/settings/account";
			path: "/settings/account";
			fullPath: "/settings/account";
			preLoaderRoute: typeof AuthenticatedDashboardSettingsSettingsAccountRouteImport;
			parentRoute: typeof AuthenticatedDashboardSettingsRoute;
		};
		"/_authenticated/_dashboard/_sales/sales/transactions": {
			id: "/_authenticated/_dashboard/_sales/sales/transactions";
			path: "/sales/transactions";
			fullPath: "/sales/transactions";
			preLoaderRoute: typeof AuthenticatedDashboardSalesSalesTransactionsRouteImport;
			parentRoute: typeof AuthenticatedDashboardSalesRoute;
		};
		"/_authenticated/_dashboard/_sales/sales/pricing": {
			id: "/_authenticated/_dashboard/_sales/sales/pricing";
			path: "/sales/pricing";
			fullPath: "/sales/pricing";
			preLoaderRoute: typeof AuthenticatedDashboardSalesSalesPricingRouteImport;
			parentRoute: typeof AuthenticatedDashboardSalesRoute;
		};
		"/_authenticated/_dashboard/_sales/sales/discount-codes": {
			id: "/_authenticated/_dashboard/_sales/sales/discount-codes";
			path: "/sales/discount-codes";
			fullPath: "/sales/discount-codes";
			preLoaderRoute: typeof AuthenticatedDashboardSalesSalesDiscountCodesRouteImport;
			parentRoute: typeof AuthenticatedDashboardSalesRoute;
		};
		"/_authenticated/_dashboard/_releases/releases/web": {
			id: "/_authenticated/_dashboard/_releases/releases/web";
			path: "/releases/web";
			fullPath: "/releases/web";
			preLoaderRoute: typeof AuthenticatedDashboardReleasesReleasesWebRouteImport;
			parentRoute: typeof AuthenticatedDashboardReleasesRoute;
		};
		"/_authenticated/_dashboard/_releases/releases/overview": {
			id: "/_authenticated/_dashboard/_releases/releases/overview";
			path: "/releases/overview";
			fullPath: "/releases/overview";
			preLoaderRoute: typeof AuthenticatedDashboardReleasesReleasesOverviewRouteImport;
			parentRoute: typeof AuthenticatedDashboardReleasesRoute;
		};
		"/_authenticated/_dashboard/_releases/releases/ios": {
			id: "/_authenticated/_dashboard/_releases/releases/ios";
			path: "/releases/ios";
			fullPath: "/releases/ios";
			preLoaderRoute: typeof AuthenticatedDashboardReleasesReleasesIosRouteImport;
			parentRoute: typeof AuthenticatedDashboardReleasesRoute;
		};
		"/_authenticated/_dashboard/_releases/releases/android": {
			id: "/_authenticated/_dashboard/_releases/releases/android";
			path: "/releases/android";
			fullPath: "/releases/android";
			preLoaderRoute: typeof AuthenticatedDashboardReleasesReleasesAndroidRouteImport;
			parentRoute: typeof AuthenticatedDashboardReleasesRoute;
		};
		"/_authenticated/_dashboard/_design/design/pages": {
			id: "/_authenticated/_dashboard/_design/design/pages";
			path: "/design/pages";
			fullPath: "/design/pages";
			preLoaderRoute: typeof AuthenticatedDashboardDesignDesignPagesRouteImport;
			parentRoute: typeof AuthenticatedDashboardDesignRoute;
		};
		"/_authenticated/_dashboard/_design/design/notifications": {
			id: "/_authenticated/_dashboard/_design/design/notifications";
			path: "/design/notifications";
			fullPath: "/design/notifications";
			preLoaderRoute: typeof AuthenticatedDashboardDesignDesignNotificationsRouteImport;
			parentRoute: typeof AuthenticatedDashboardDesignRoute;
		};
		"/_authenticated/_dashboard/_design/design/layout": {
			id: "/_authenticated/_dashboard/_design/design/layout";
			path: "/design/layout";
			fullPath: "/design/layout";
			preLoaderRoute: typeof AuthenticatedDashboardDesignDesignLayoutRouteImport;
			parentRoute: typeof AuthenticatedDashboardDesignRoute;
		};
		"/_authenticated/_dashboard/_design/design/branding": {
			id: "/_authenticated/_dashboard/_design/design/branding";
			path: "/design/branding";
			fullPath: "/design/branding";
			preLoaderRoute: typeof AuthenticatedDashboardDesignDesignBrandingRouteImport;
			parentRoute: typeof AuthenticatedDashboardDesignRoute;
		};
	}
}

interface AuthenticatedDashboardDesignRouteChildren {
	AuthenticatedDashboardDesignDesignBrandingRoute: typeof AuthenticatedDashboardDesignDesignBrandingRoute;
	AuthenticatedDashboardDesignDesignLayoutRoute: typeof AuthenticatedDashboardDesignDesignLayoutRoute;
	AuthenticatedDashboardDesignDesignNotificationsRoute: typeof AuthenticatedDashboardDesignDesignNotificationsRoute;
	AuthenticatedDashboardDesignDesignPagesRoute: typeof AuthenticatedDashboardDesignDesignPagesRoute;
}

const AuthenticatedDashboardDesignRouteChildren: AuthenticatedDashboardDesignRouteChildren =
	{
		AuthenticatedDashboardDesignDesignBrandingRoute:
			AuthenticatedDashboardDesignDesignBrandingRoute,
		AuthenticatedDashboardDesignDesignLayoutRoute:
			AuthenticatedDashboardDesignDesignLayoutRoute,
		AuthenticatedDashboardDesignDesignNotificationsRoute:
			AuthenticatedDashboardDesignDesignNotificationsRoute,
		AuthenticatedDashboardDesignDesignPagesRoute:
			AuthenticatedDashboardDesignDesignPagesRoute,
	};

const AuthenticatedDashboardDesignRouteWithChildren =
	AuthenticatedDashboardDesignRoute._addFileChildren(
		AuthenticatedDashboardDesignRouteChildren,
	);

interface AuthenticatedDashboardMembersRouteChildren {
	AuthenticatedDashboardMembersMembersIndexRoute: typeof AuthenticatedDashboardMembersMembersIndexRoute;
}

const AuthenticatedDashboardMembersRouteChildren: AuthenticatedDashboardMembersRouteChildren =
	{
		AuthenticatedDashboardMembersMembersIndexRoute:
			AuthenticatedDashboardMembersMembersIndexRoute,
	};

const AuthenticatedDashboardMembersRouteWithChildren =
	AuthenticatedDashboardMembersRoute._addFileChildren(
		AuthenticatedDashboardMembersRouteChildren,
	);

interface AuthenticatedDashboardReleasesRouteChildren {
	AuthenticatedDashboardReleasesReleasesAndroidRoute: typeof AuthenticatedDashboardReleasesReleasesAndroidRoute;
	AuthenticatedDashboardReleasesReleasesIosRoute: typeof AuthenticatedDashboardReleasesReleasesIosRoute;
	AuthenticatedDashboardReleasesReleasesOverviewRoute: typeof AuthenticatedDashboardReleasesReleasesOverviewRoute;
	AuthenticatedDashboardReleasesReleasesWebRoute: typeof AuthenticatedDashboardReleasesReleasesWebRoute;
}

const AuthenticatedDashboardReleasesRouteChildren: AuthenticatedDashboardReleasesRouteChildren =
	{
		AuthenticatedDashboardReleasesReleasesAndroidRoute:
			AuthenticatedDashboardReleasesReleasesAndroidRoute,
		AuthenticatedDashboardReleasesReleasesIosRoute:
			AuthenticatedDashboardReleasesReleasesIosRoute,
		AuthenticatedDashboardReleasesReleasesOverviewRoute:
			AuthenticatedDashboardReleasesReleasesOverviewRoute,
		AuthenticatedDashboardReleasesReleasesWebRoute:
			AuthenticatedDashboardReleasesReleasesWebRoute,
	};

const AuthenticatedDashboardReleasesRouteWithChildren =
	AuthenticatedDashboardReleasesRoute._addFileChildren(
		AuthenticatedDashboardReleasesRouteChildren,
	);

interface AuthenticatedDashboardSalesRouteChildren {
	AuthenticatedDashboardSalesSalesDiscountCodesRoute: typeof AuthenticatedDashboardSalesSalesDiscountCodesRoute;
	AuthenticatedDashboardSalesSalesPricingRoute: typeof AuthenticatedDashboardSalesSalesPricingRoute;
	AuthenticatedDashboardSalesSalesTransactionsRoute: typeof AuthenticatedDashboardSalesSalesTransactionsRoute;
}

const AuthenticatedDashboardSalesRouteChildren: AuthenticatedDashboardSalesRouteChildren =
	{
		AuthenticatedDashboardSalesSalesDiscountCodesRoute:
			AuthenticatedDashboardSalesSalesDiscountCodesRoute,
		AuthenticatedDashboardSalesSalesPricingRoute:
			AuthenticatedDashboardSalesSalesPricingRoute,
		AuthenticatedDashboardSalesSalesTransactionsRoute:
			AuthenticatedDashboardSalesSalesTransactionsRoute,
	};

const AuthenticatedDashboardSalesRouteWithChildren =
	AuthenticatedDashboardSalesRoute._addFileChildren(
		AuthenticatedDashboardSalesRouteChildren,
	);

interface AuthenticatedDashboardSettingsRouteChildren {
	AuthenticatedDashboardSettingsSettingsAccountRoute: typeof AuthenticatedDashboardSettingsSettingsAccountRoute;
	AuthenticatedDashboardSettingsSettingsBillingRoute: typeof AuthenticatedDashboardSettingsSettingsBillingRoute;
	AuthenticatedDashboardSettingsSettingsIntegrationsRoute: typeof AuthenticatedDashboardSettingsSettingsIntegrationsRoute;
	AuthenticatedDashboardSettingsSettingsNotificationsRoute: typeof AuthenticatedDashboardSettingsSettingsNotificationsRoute;
}

const AuthenticatedDashboardSettingsRouteChildren: AuthenticatedDashboardSettingsRouteChildren =
	{
		AuthenticatedDashboardSettingsSettingsAccountRoute:
			AuthenticatedDashboardSettingsSettingsAccountRoute,
		AuthenticatedDashboardSettingsSettingsBillingRoute:
			AuthenticatedDashboardSettingsSettingsBillingRoute,
		AuthenticatedDashboardSettingsSettingsIntegrationsRoute:
			AuthenticatedDashboardSettingsSettingsIntegrationsRoute,
		AuthenticatedDashboardSettingsSettingsNotificationsRoute:
			AuthenticatedDashboardSettingsSettingsNotificationsRoute,
	};

const AuthenticatedDashboardSettingsRouteWithChildren =
	AuthenticatedDashboardSettingsRoute._addFileChildren(
		AuthenticatedDashboardSettingsRouteChildren,
	);

interface AuthenticatedDashboardRouteChildren {
	AuthenticatedDashboardDesignRoute: typeof AuthenticatedDashboardDesignRouteWithChildren;
	AuthenticatedDashboardMembersRoute: typeof AuthenticatedDashboardMembersRouteWithChildren;
	AuthenticatedDashboardReleasesRoute: typeof AuthenticatedDashboardReleasesRouteWithChildren;
	AuthenticatedDashboardSalesRoute: typeof AuthenticatedDashboardSalesRouteWithChildren;
	AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRouteWithChildren;
	AuthenticatedDashboardMediaRoute: typeof AuthenticatedDashboardMediaRoute;
	AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute;
	AuthenticatedDashboardProductsProductIdRoute: typeof AuthenticatedDashboardProductsProductIdRoute;
	AuthenticatedDashboardProductsIndexRoute: typeof AuthenticatedDashboardProductsIndexRoute;
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
	{
		AuthenticatedDashboardDesignRoute:
			AuthenticatedDashboardDesignRouteWithChildren,
		AuthenticatedDashboardMembersRoute:
			AuthenticatedDashboardMembersRouteWithChildren,
		AuthenticatedDashboardReleasesRoute:
			AuthenticatedDashboardReleasesRouteWithChildren,
		AuthenticatedDashboardSalesRoute:
			AuthenticatedDashboardSalesRouteWithChildren,
		AuthenticatedDashboardSettingsRoute:
			AuthenticatedDashboardSettingsRouteWithChildren,
		AuthenticatedDashboardMediaRoute: AuthenticatedDashboardMediaRoute,
		AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
		AuthenticatedDashboardProductsProductIdRoute:
			AuthenticatedDashboardProductsProductIdRoute,
		AuthenticatedDashboardProductsIndexRoute:
			AuthenticatedDashboardProductsIndexRoute,
	};

const AuthenticatedDashboardRouteWithChildren =
	AuthenticatedDashboardRoute._addFileChildren(
		AuthenticatedDashboardRouteChildren,
	);

interface AuthenticatedOnboardingRouteChildren {
	AuthenticatedOnboardingOnboardingPlanRoute: typeof AuthenticatedOnboardingOnboardingPlanRoute;
	AuthenticatedOnboardingOnboardingProductRoute: typeof AuthenticatedOnboardingOnboardingProductRoute;
	AuthenticatedOnboardingOnboardingProfileRoute: typeof AuthenticatedOnboardingOnboardingProfileRoute;
	AuthenticatedOnboardingOnboardingWorkspaceRoute: typeof AuthenticatedOnboardingOnboardingWorkspaceRoute;
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
	{
		AuthenticatedOnboardingOnboardingPlanRoute:
			AuthenticatedOnboardingOnboardingPlanRoute,
		AuthenticatedOnboardingOnboardingProductRoute:
			AuthenticatedOnboardingOnboardingProductRoute,
		AuthenticatedOnboardingOnboardingProfileRoute:
			AuthenticatedOnboardingOnboardingProfileRoute,
		AuthenticatedOnboardingOnboardingWorkspaceRoute:
			AuthenticatedOnboardingOnboardingWorkspaceRoute,
	};

const AuthenticatedOnboardingRouteWithChildren =
	AuthenticatedOnboardingRoute._addFileChildren(
		AuthenticatedOnboardingRouteChildren,
	);

interface AuthenticatedRouteChildren {
	AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren;
	AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
	AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
	AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
	AuthenticatedRouteChildren,
);

interface LoginRouteChildren {
	LoginLoginCodeRoute: typeof LoginLoginCodeRoute;
	LoginLoginIndexRoute: typeof LoginLoginIndexRoute;
}

const LoginRouteChildren: LoginRouteChildren = {
	LoginLoginCodeRoute: LoginLoginCodeRoute,
	LoginLoginIndexRoute: LoginLoginIndexRoute,
};

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	AuthenticatedRoute: AuthenticatedRouteWithChildren,
	LoginRoute: LoginRouteWithChildren,
	ApiSplatRoute: ApiSplatRoute,
	AuthSplatRoute: AuthSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
